name: Release CLI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Generate version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"

      - name: Write version in the main file
        run: sed -i "s/__VERSION__/${{ steps.version.outputs.version }}/g" ./src/main.ts

      - name: Build CLI for aarch64-apple-darwin
        run: |
          export COMPILE_TARGET=aarch64-apple-darwin
          export COMPILE_NAME=dot-darwin-arm64
          deno run compile

      - name: Build CLI for x86_64-apple-darwin
        run: |
          export COMPILE_TARGET=x86_64-apple-darwin
          export COMPILE_NAME=dot-darwin-x64
          deno run compile

      - name: Build CLI for x86_64-unknown-linux-gnu
        run: |
          export COMPILE_TARGET=x86_64-unknown-linux-gnu
          export COMPILE_NAME=dot-linux-x64
          deno run compile

      - name: Build CLI for aarch64-unknown-linux-gnu
        run: |
          export COMPILE_TARGET=aarch64-unknown-linux-gnu
          export COMPILE_NAME=dot-linux-arm64
          deno run compile

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: ./build/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
